//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saafcity_fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complainnt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complainnt()
        {
            this.Complaints = new HashSet<Complaint>();
        }
    
        public int Complainant_ID { get; set; }
        public string Complainant_Name { get; set; }
        public string Complainant_Email { get; set; }
        public string Complainant_PhoneNo { get; set; }
        public string Complainant_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
    }
}
