//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saafcity_fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint_Log
    {
        public int Serial_No { get; set; }
        public Nullable<int> Complaint_ID { get; set; }
        public Nullable<System.TimeSpan> Log_Time { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public string Complaint_Loction { get; set; }
        public string Complaint_Status { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Depart_ID { get; set; }
        public string Comments { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
